package com.fresnohernandez99.stpt.presentation.home

import com.fresnohernandez99.stpt.domain.model.Language

data class HomeUiState(
    val textToTranslate: String = "",
    val sourceLanguage: Language = Language.Detect,
    val targetLanguage: Language = Language.Spanish,
    val translatedText: String = "",
    val isTranslating: Boolean = false,

    val languages: List<Language> = listOf(
        // TODO Language.Detect,
        // Idiomas de mayor interés para Latinoamérica
        Language("en", "English", "🇺🇸"),
        Language("pt", "Portuguese", "🇧🇷"),
        Language("zh", "Chinese", "🇨🇳"),
        Language("yue", "Cantonese", "🇭🇰"),
        Language("fr", "French", "🇫🇷"),
        Language("de", "German", "🇩🇪"),
        Language("it", "Italian", "🇮🇹"),
        Language("ja", "Japanese", "🇯🇵"),
        Language("ko", "Korean", "🇰🇷"),

        // Resto de la lista en orden alfabético
        Language("af", "Afrikaans", "🇿🇦"),
        Language("am", "Amharic", "🇪🇹"),
        Language("ar", "Arabic", "🇸🇦"),
        Language("as", "Assamese", "🇮🇳"),
        Language("az", "Azerbaijani", "🇦🇿"),
        Language("ba", "Bashkir", "🇷🇺"),
        Language("be", "Belarusian", "🇧🇾"),
        Language("bg", "Bulgarian", "🇧🇬"),
        Language("bn", "Bengali", "🇧 Bangladesh"),
        Language("bo", "Tibetan", "🇨🇳"),
        Language("br", "Breton", "🇫🇷"),
        Language("bs", "Bosnian", "🇧🇦"),
        Language("ca", "Catalan", "🇪🇸"),
        Language("cs", "Czech", "🇨🇿"),
        Language("cy", "Welsh", "🇬🇧"),
        Language("da", "Danish", "🇩🇰"),
        Language("el", "Greek", "🇬🇷"),
        Language.Spanish,
        Language("et", "Estonian", "🇪🇪"),
        Language("eu", "Basque", "🇪🇸"),
        Language("fa", "Persian", "🇮🇷"),
        Language("fi", "Finnish", "🇫🇮"),
        Language("fo", "Faroese", "🇫🇴"),
        Language("gl", "Galician", "🇪🇸"),
        Language("gu", "Gujarati", "🇮🇳"),
        Language("ha", "Hausa", "🇳🇬"),
        Language("haw", "Hawaiian", "🇺🇸"),
        Language("he", "Hebrew", "🇮🇱"),
        Language("hi", "Hindi", "🇮🇳"),
        Language("hr", "Croatian", "🇭🇷"),
        Language("ht", "Haitian Creole", "🇭🇹"),
        Language("hu", "Hungarian", "🇭🇺"),
        Language("hy", "Armenian", "🇦🇲"),
        Language("id", "Indonesian", "🇮🇩"),
        Language("is", "Icelandic", "🇮🇸"),
        Language("jv", "Javanese", "🇮🇩"),
        Language("ka", "Georgian", "🇬🇪"),
        Language("kk", "Kazakh", "🇰🇿"),
        Language("km", "Khmer", "🇰🇭"),
        Language("kn", "Kannada", "🇮🇳"),
        Language("la", "Latin", "🇻🇦"),
        Language("lb", "Luxembourgish", "🇱🇺"),
        Language("ln", "Lingala", "🇨🇩"),
        Language("lo", "Lao", "🇱🇦"),
        Language("lt", "Lithuanian", "🇱🇹"),
        Language("lv", "Latvian", "🇱🇻"),
        Language("mg", "Malagasy", "🇲🇬"),
        Language("mi", "Maori", "🇳🇿"),
        Language("mk", "Macedonian", "🇲🇰"),
        Language("ml", "Malayalam", "🇮🇳"),
        Language("mn", "Mongolian", "🇲🇳"),
        Language("mr", "Marathi", "🇮🇳"),
        Language("ms", "Malay", "🇲🇾"),
        Language("mt", "Maltese", "🇲🇹"),
        Language("my", "Myanmar", "🇲🇲"),
        Language("ne", "Nepali", "🇳🇵"),
        Language("nl", "Dutch", "🇳🇱"),
        Language("nn", "Norwegian Nynorsk", "🇳🇴"),
        Language("no", "Norwegian", "🇳🇴"),
        Language("oc", "Occitan", "🇫🇷"),
        Language("pa", "Punjabi", "🇮🇳"),
        Language("pl", "Polish", "🇵🇱"),
        Language("ps", "Pashto", "🇦🇫"),
        Language("ro", "Romanian", "🇷🇴"),
        Language("ru", "Russian", "🇷🇺"),
        Language("sa", "Sanskrit", "🇮🇳"),
        Language("sd", "Sindhi", "🇵🇰"),
        Language("si", "Sinhala", "🇱🇰"),
        Language("sk", "Slovak", "🇸🇰"),
        Language("sl", "Slovenian", "🇸🇮"),
        Language("sn", "Shona", "🇿🇼"),
        Language("so", "Somali", "🇸🇴"),
        Language("sq", "Albanian", "🇦🇱"),
        Language("sr", "Serbian", "🇷🇸"),
        Language("su", "Sundanese", "🇮🇩"),
        Language("sv", "Swedish", "🇸🇪"),
        Language("sw", "Swahili", "🇰🇪"),
        Language("ta", "Tamil", "🇮🇳"),
        Language("te", "Telugu", "🇮🇳"),
        Language("tg", "Tajik", "🇹🇯"),
        Language("th", "Thai", "🇹🇭"),
        Language("tk", "Turkmen", "🇹🇲"),
        Language("tl", "Tagalog", "🇵🇭"),
        Language("tr", "Turkish", "🇹🇷"),
        Language("tt", "Tatar", "🇷🇺"),
        Language("uk", "Ukrainian", "🇺🇦"),
        Language("ur", "Urdu", "🇵🇰"),
        Language("uz", "Uzbek", "🇺🇿"),
        Language("vi", "Vietnamese", "🇻🇳"),
        Language("yi", "Yiddish", "✡️"),
        Language("yo", "Yoruba", "🇳🇬")
    )
)
